### ISSUE TITLE
iOScreator - Take Video Tutorial in iOS8 with Swift

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#100]
原文标题：Take Video Tutorial in iOS8 with Swift
原文链接：http://www.ioscreator.com/tutorials/take-video-tutorial-ios8-swift
注：iOScreator的站长要求我们注明文章来源，这个切记！

**Comment by hehonghui** [comment]
@bboyfeiyu 认领。
