### ISSUE TITLE
iOScreator - Play Music with AVAudioPlayer in iOS8 with Swift

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#101]
原文标题：Play Music with AVAudioPlayer in iOS8 with Swift
原文链接：http://www.ioscreator.com/tutorials/play-music-avaudioplayer-ios8-swift
注：iOScreator的站长要求我们注明文章来源，这个切记！

**Comment by mrchenhao** [comment]
@mrchenhao AV让我来

**Comment by StormXX** [comment]
@mrchenhao 好的好的。。。。。。。。
