### ISSUE TITLE
iOScreator - Add Search to Table View Tutorial in iOS8 with Swift

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#102]
原文标题：Add Search to Table View Tutorial in iOS8 with Swift
原文链接：http://www.ioscreator.com/tutorials/add-search-table-view-tutorial-ios8-swift
注：iOScreator的站长要求我们注明文章来源，这个切记！

**Comment by StormXX** [comment]
@StormXX

**Comment by hehonghui** [comment]
@StormXX 你翻译这篇吗  ？

**Comment by StormXX** [comment]
@bboyfeiyu 是的= =。你要这篇咩？

**Comment by hehonghui** [comment]
@StormXX 我看你没有标记翻译中，所以问问罢了。我领另外一篇吧。
