### ISSUE TITLE
THE RIGHT WAY TO WRITE A SINGLETON

### ISSUE THREAD

**Issue by mrchenhao** [bboyfeiyu/iOS-tech-frontier#105]
Swift实现单例模式
URL:http://krakendev.io/blog/the-right-way-to-write-a-singleton?utm_campaign=This%2BWeek%2Bin%2BSwift&utm_medium=web&utm_source=This_Week_in_Swift_45

**Comment by Gottabe** [comment]
i take it

**Comment by bboyfeiyu** [comment]
@Gottabe 多谢贡献
