### ISSUE TITLE
Introducing iOS Design Patterns in Swift – Part 1/2

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#113]
原文链接：http://www.raywenderlich.com/86477/introducing-ios-design-patterns-in-swift-part-1
推荐理由：介绍iOS设计模式(Swift实现)

**Comment by alier1226** [comment]
@alier1226

**Comment by alier1226** [comment]
有点长啊，估计得两周。刚开学学校一堆事(ˊ·ω·`)
