### ISSUE TITLE
iOS 9 App Search Tutorial: Introduction to App Search

### ISSUE THREAD

**Issue by MrLoong** [bboyfeiyu/iOS-tech-frontier#123]
原文链接：http://www.raywenderlich.com/116608/ios-9-app-search-tutorial-introduction-to-app-search
iOS9教程关于搜索的

**Comment by kmyhy** [comment]
@kmyhy 认领

**Comment by kmyhy** [comment]
iOS 9 App Search 教程翻译完成。

**Comment by mrchenhao** [comment]
@kmyhy  好了 我合进去了 感谢你噢
