### ISSUE TITLE
UIStackView Tutorial: Introducing Stack Views

### ISSUE THREAD

**Issue by MrLoong** [bboyfeiyu/iOS-tech-frontier#125]
原文链接：http://www.raywenderlich.com/114552/uistackview-tutorial-introducing-stack-views

引入栈视图

**Comment by kmyhy** [comment]
@kmyhy 认领

**Comment by MrLoong** [comment]
@kmyhy OK       谢谢参与哈

**Comment by kmyhy** [comment]
UIStackView教程：了解Stack View
翻译完成，已Pull request

**Comment by mrchenhao** [comment]
已经merge close
