### ISSUE TITLE
Grand Central Dispatch (GCD): Summary, Syntax & Best Practices

### ISSUE THREAD

**Issue by hysteriaheaven** [bboyfeiyu/iOS-tech-frontier#15]
推荐理由：GCD的语法、最佳实践及非常好的总结
链接：http://amattn.com/p/grand_central_dispatch_gcd_summary_syntax_best_practices.html
标签：iOS、GCD

**Comment by starmier** [comment]
认领

**Comment by hysteriaheaven** [comment]
@hysteriaheaven
