### ISSUE TITLE
cloudkit-introduction-tutorial

### ISSUE THREAD

**Issue by mrchenhao** [bboyfeiyu/iOS-tech-frontier#19]
http://www.appcoda.com/cloudkit-introduction-tutorial/
一篇关于iCloud的入门介绍，写的不错

**Comment by mrchenhao** [comment]
认领

**Comment by bboyfeiyu** [comment]
@mrchenhao 这篇是啥情况 ？

**Comment by mrchenhao** [comment]
@bboyfeiyu  这篇原文有点长 ，有些地方还在修改，再过一两天提交

**Comment by bboyfeiyu** [comment]
@mrchenhao 是怕你忘记了哈，辛苦了。 :+1:
