### ISSUE TITLE
3 Nuances of Swift Extensions

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#20]
推荐理由：3 Nuances of Swift Extensions
原文链接：http://www.andrewcbancroft.com/2015/04/22/3-nuances-of-swift-extensions/

**Comment by ghost** [comment]
我来翻译试试

**Comment by hehonghui** [comment]
@samw00 好的，谢啦。

**Comment by mrchenhao** [comment]
校对完成 close
