### ISSUE TITLE
How Delegation Works – A Swift Developer’s Guide

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#21]
推荐理由：How Delegation Works – A Swift Developer’s Guide
原文链接：http://www.andrewcbancroft.com/2015/04/08/how-delegation-works-a-swift-developer-guide/

**Comment by xu6148152** [comment]
@xu6148152

**Comment by hehonghui** [comment]
@sdq 你看看这篇呗？也是关于代理的 :)

**Comment by hehonghui** [comment]
@sdq 这篇你是否翻译？
