### ISSUE TITLE
What is Delegation? – A Swift Developer’s Guide

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#22]
推荐理由：Swift委托是什么
原文链接：http://www.andrewcbancroft.com/2015/03/26/what-is-delegation-a-swift-developers-guide/

**Comment by xu6148152** [comment]
@xu6148152

**Comment by StormXX** [comment]
@xu6148152 你是认领翻译吗？

**Comment by xu6148152** [comment]
@StormXX yeah

**Comment by hehonghui** [comment]
@xu6148152 没时间翻译了，@StormXX 你看看有哪位愿意翻译一下呗

**Comment by sdq** [comment]
@sdq 交给我吧~
