### ISSUE TITLE
Clarifying Swift Access Control (Hint: Swift Isn’t C#)

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#23]
推荐理由:Clarifying Swift Access Control (Hint: Swift Isn’t C#)
原文链接：http://www.andrewcbancroft.com/2015/04/24/clarifying-swift-access-control-hint-swift-isnt-c-sharp/

**Comment by StormXX** [comment]
我来翻译

**Comment by StormXX** [comment]
@bboyfeiyu 这个搁置了好久，还需要这篇吗？
