### ISSUE TITLE
Jared’s Code Signing Tips: Apple Watch Edition

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#24]
推荐理由：Jared’s Code Signing Tips: Apple Watch Edition
原文链接：http://blog.jaredsinclair.com/post/117350678170

**Comment by samlaudev** [comment]
@samlaudev 领取该翻译任务

**Comment by MrLoong** [comment]
[@MrLoong](https://github.com/MrLoong) 认领
