### ISSUE TITLE
关于AFNetworking 安全bug的回复

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/iOS-tech-frontier#31]
- 推荐理由 : 关于AFNetworking 安全bug的回复
- 原文链接 : https://gist.github.com/AlamofireSoftwareFoundation/f784f18f949b95ab733a?utm_campaign=iOS_Dev_Weekly_Issue_196&utm_medium=email&utm_source=iOS%2BDev%2BWeekly

**Comment by ghost** [comment]
@Lollypo Me
