### ISSUE TITLE
Core Graphics Tutorial Part 1: Getting Started

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#36]
推荐理由：Swift 的 Core Graphics系列教程 高质量文章 绘图相关
原文地址：http://www.raywenderlich.com/90690/modern-core-graphics-with-swift-part-1

**Comment by StormXX** [comment]
@StormXX

**Comment by hehonghui** [comment]
@StormXX 你有管理权限，认领文章的时候可以自行修改状态哈。:)

**Comment by sdq** [comment]
@sdq 共同翻译第一篇。取消第二篇的翻译

**Comment by hehonghui** [comment]
@sdq 已经和 @StormXX 沟通了吗 ？

**Comment by sdq** [comment]
恩，沟通好了哦

**Comment by StormXX** [comment]
已完成~
