### ISSUE TITLE
Core Graphics Tutorial Part 2: Gradients and Contexts

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#37]
推荐理由：Swift 的 Core Graphics系列教程 高质量文章 绘图相关（第二篇）
原文地址：http://www.raywenderlich.com/90693/modern-core-graphics-with-swift-part-2

**Comment by sdq** [comment]
@sdq

**Comment by sdq** [comment]
去翻译第一篇了哦，请把状态再改回“待认领”

**Comment by hehonghui** [comment]
我翻译这篇。

**Comment by mrchenhao** [comment]
加入翻译
