### ISSUE TITLE
Core Graphics Tutorial Part 3: Patterns and Playgrounds

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#38]
推荐理由：Swift 的 Core Graphics系列教程 高质量文章 绘图相关（第三篇）
原文地址：http://www.raywenderlich.com/90695/modern-core-graphics-with-swift-part-3

**Comment by MrLoong** [comment]
[@MrLong](https://github.com/)认领

**Comment by hehonghui** [comment]
@MrLoong 认真翻译哈

**Comment by MrLoong** [comment]
@bboyfeiyu 肯定认真翻译啊
