### ISSUE TITLE
Strong, Weak, and Unowned – Sorting out ARC and Swift

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/iOS-tech-frontier#40]
推荐理由：Strong, Weak, and Unowned – Sorting out ARC and Swift
原文链接：http://www.andrewcbancroft.com/2015/05/08/strong-weak-and-unowned-sorting-out-arc-and-swift/

**Comment by ghost** [comment]
我来翻译

**Comment by hehonghui** [comment]
@samw00 学生吗?

**Comment by ghost** [comment]
@bboyfeiyu 不是了，T.T 呜呜

**Comment by hehonghui** [comment]
@samw00 说多了都是泪啊~
