### ISSUE TITLE
关于swift扩展访问控制

### ISSUE THREAD

**Issue by ValiantCat** [bboyfeiyu/iOS-tech-frontier#49]
在swift  访问控制 不是按照class 来分配的  而是按照文件来分配的  所以private 只要在同一个文件中 就是可以访问的 无论是扩展 还是其他类

**Comment by StormXX** [comment]
@aiqiuqiu  恩？这是什么？是不是评论错地方了？

**Comment by ValiantCat** [comment]
https://github.com/bboyfeiyu/iOS-tech-frontier/blob/master/issue-4/Swift%E6%89%A9%E5%B1%95%E7%9A%84%E4%B8%89%E4%B8%AA%E5%BE%AE%E5%A6%99%E7%BB%86%E8%8A%82.md

**Comment by StormXX** [comment]
@samw00 @bboyfeiyu 看看是不是校对的问题？我没有找到是哪一句

**Comment by ValiantCat** [comment]
没有写错  是理解多了    我的意思是这篇文章就讲的不对
