### ISSUE TITLE
iOS Animation Tutorial: Getting Started

### ISSUE THREAD

**Issue by samlaudev** [bboyfeiyu/iOS-tech-frontier#54]
推荐理由：iOS Animation Tutorial: Getting Started
原文链接：http://www.raywenderlich.com/95910/uiview-animation-swift-tutorial

**Comment by mrchenhao** [comment]
认领

**Comment by ghost** [comment]
昨天刚看完这本书的第一节,发现内容完全差不多啊

**Comment by mrchenhao** [comment]
哪本书呢  iOS Animation？

**Comment by ghost** [comment]
恩,就是RW上的那本动画的.第一章第一节就是这个博客的内容.这是我完成第一节的效果图
http://a3.qpic.cn/psb?/V13bAJnZ4YAnSO/df94fP*hnWfkHXg*wcHucomWq1krEzKvNxHPs1lWe7w!/b/dB4AAAAAAAAA&ek=1&kp=1&pt=0&bo=bgGuAm4BrgICCCw!&sce=0-12-12&rf=0-18
