### ISSUE TITLE
iOS Animation Tutorial: Custom View Controller Presentation Transitions

### ISSUE THREAD

**Issue by samlaudev** [bboyfeiyu/iOS-tech-frontier#55]
推荐理由：iOS Animation Tutorial: Custom View Controller Presentation Transitions
原文链接：http://www.raywenderlich.com/96062/custom-view-controller-presentation-transitions-swift

**Comment by sdq** [comment]
@sdq 认领

**Comment by MrLoong** [comment]
[@MrLoong认领](https://github.com/MrLoong)

**Comment by samlaudev** [comment]
@sdq @MrLoong 你们两个一起翻译吗？

**Comment by sdq** [comment]
@samlaudev @MrLoong  没联系过呢，没事我还没翻，就让 @MrLoong 翻译吧~

**Comment by MrLoong** [comment]
@samlaudev 都可以     我以为sdq没有认领呢

**Comment by hehonghui** [comment]
@bboyfeiyu 这篇不是给sdq了吗？
