### ISSUE TITLE
在 Swift 中实现 Future/Promise 模式

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/iOS-tech-frontier#60]
- 原文链接 : http://realm.io/news/swift-summit-javier-soto-futures/

**Comment by sdq** [comment]
@sdq 认领。 学习一下~

**Comment by hehonghui** [comment]
@sdq 给你管理权限了哈~

**Comment by sdq** [comment]
@bboyfeiyu 好的~

**Comment by jiharley** [comment]
@jiharley 共同翻译

**Comment by hehonghui** [comment]
@jiharley 这篇文章挺长时间了 ？啥进度呢 ？ :)

**Comment by sdq** [comment]
@bboyfeiyu  这段时间比较忙，翻了一半，这周末翻译出来

**Comment by jiharley** [comment]
@bboyfeiyu 我前段时间有些紧急的事情处理，跟@sdq 商量后这篇文章现在是他在翻译，抱歉~ 有机会我再翻译别的
