### ISSUE TITLE
changes-to-the-swift-standard-library-in-2-0-beta-1

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/iOS-tech-frontier#75]
- 原文链接 : [changes-to-the-swift-standard-library-in-2-0-beta-1](http://airspeedvelocity.net/2015/06/09/changes-to-the-swift-standard-library-in-2-0-beta-1/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS_Dev_Weekly_Issue_202)

**Comment by ghost** [comment]
认领，原文的配色看起来很费劲啊
![snip20150625_1](https://cloud.githubusercontent.com/assets/11835866/8356171/5514a3e2-1b86-11e5-9158-73435f31ac0a.png)

**Comment by ghost** [comment]
由@samw00 认领
