### ISSUE TITLE
iOS中的依赖注入

### ISSUE THREAD

**Issue by hehonghui** [bboyfeiyu/iOS-tech-frontier#83]
[https://corner.squareup.com/2015/06/dependency-injection-in-objc.html](https://corner.squareup.com/2015/06/dependency-injection-in-objc.html)

**Comment by mrchenhao** [comment]
我来

**Comment by hehonghui** [comment]
@mrchenhao 有啥好文章来源么 ？ 咱这来源太少了。

**Comment by mrchenhao** [comment]
@bboyfeiyu  我刚在medium上找文章呢   感觉最近的新文章有点少  得花点时间找找

**Comment by hehonghui** [comment]
@mrchenhao 不能只通过那种渠道了，可以看看ios,swift的外国的周报，不然咱们的来源太少了。

**Comment by mrchenhao** [comment]
@bboyfeiyu  我订阅了https://github.com/iOS-Goodies/iOS-Goodies  感觉还是不错滴   周报

**Comment by hehonghui** [comment]
@mrchenhao 还有其他的weekly你可以订阅一下哈，swift, ios 都有weekly。只要文章不错，都可以提过来。

**Comment by mrchenhao** [comment]
@bboyfeiyu  好的  不过这种需不需要和那些收集的人打个招呼
