### ISSUE TITLE
Auto Layout Tutorial Part 1: Getting Started

### ISSUE THREAD

**Issue by mrchenhao** [bboyfeiyu/iOS-tech-frontier#87]
Auto Layout Tutorial Part 1: Getting Started
推荐理由：iOS9即将来临，自动布局势在必行
地址：http://www.raywenderlich.com/83129/beginning-auto-layout-tutorial-swift-part-1

**Comment by MollyMmm** [comment]
@MollyMmm认领

**Comment by MollyMmm** [comment]
@MollyMmm 该教程更新到ios9,目前开始重新翻译
