### ISSUE TITLE
Introducing Protocol-Oriented Programming in Swift 2

### ISSUE THREAD

**Issue by ghost** [bboyfeiyu/iOS-tech-frontier#92]
推荐理由：介绍Swift2的面向协议编程
连接：http://www.raywenderlich.com/109156/introducing-protocol-oriented-programming-in-swift-2

**Comment by StormXX** [comment]
@StormXX

**Comment by hehonghui** [comment]
@StormXX 这篇你翻译了么 ？如果没有的话我处理一下。

**Comment by StormXX** [comment]
@bboyfeiyu 没有，这几天项目上新版本。暂时没时间~是close还是继续留着呢？

**Comment by hehonghui** [comment]
@StormXX 留着吧，我有时间翻译一下，这周没有iOS的了。

**Comment by StormXX** [comment]
@bboyfeiyu 好的~这几天太忙了。那边ioscreator也联系好了，等我这周新版本上线之后我有空了在群里说一下和添加一下文章来源。那边的很多文章应该都可以搬过来翻译。组织一波翻译。浩浩马上也要来入职我公司了哈哈哈哈

**Comment by sdq** [comment]
这篇还没翻？ @StormXX 
貌似已经有人翻译了
http://www.swiftyper.com/Swift/introducing-protocol-oriented-programming-in-swift-2.html
