### ISSUE TITLE
File Management Tutorial in iOS8 with Swift

### ISSUE THREAD

**Issue by mrchenhao** [bboyfeiyu/iOS-tech-frontier#94]
File Management Tutorial in iOS8 with Swift
推荐理由: Swift文件管理
http://www.ioscreator.com/tutorials/file-management-tutorial-ios8-swift

**Comment by Lollypo** [comment]
@mrchenhao 链接呢

**Comment by StormXX** [comment]
@Lollypo 链接放了

**Comment by Lollypo** [comment]
@StormXX 搜噶，之前没看到

**Comment by mrchenhao** [comment]
@mrchenhao 自己来
