### ISSUE TITLE
How to Create a CocoaPod in Swift-创建自己的cocoaPod

### ISSUE THREAD

**Issue by StormXX** [bboyfeiyu/iOS-tech-frontier#96]
原文地址：http://www.raywenderlich.com/99386/create-cocoapod-swift

**Comment by MrLoong** [comment]
[@MrLoong](https://github.com/MrLoong)    认领     马上考试周了，很久没有翻译了，考试周之前翻译一篇

**Comment by MrLoong** [comment]
?

**Comment by MrLoong** [comment]
@StormXX  求认领

**Comment by StormXX** [comment]
@MrLoong OK~认领只要艾特自己就好啦~我们看到就会改Label的~我昨天在坐火车，所以没开电脑。不好意思~

**Comment by StormXX** [comment]
@MrLoong 这篇怎么样了？

**Comment by MrLoong** [comment]
@StormXX 还差一些    这几天都有考试   大概在3天后吧
