### ISSUE TITLE
Brigade’s Experience Using an MVC Alternative--VIPER architecture for iOS applications

### ISSUE THREAD

**Issue by mrchenhao** [bboyfeiyu/iOS-tech-frontier#99]
介绍viper
URL:https://medium.com/brigade-engineering/brigades-experience-using-an-mvc-alternative-36ef1601a41f

**Comment by MrLoong** [comment]
[@MrLoong 认领]{https://github.com/MrLoong}

**Comment by MrLoong** [comment]
@MrLoong

**Comment by MrLoong** [comment]
@MrLoong认领

**Comment by MrLoong** [comment]
@MrLoong认领

**Comment by Quzhiyu** [comment]
@Quzhiyu
